name: aws_ai
description: Flutter package to wrap Amazon artificial intelligence services
version: 0.0.3
homepage: https://github.com/mrahman4/aws-ai

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  async: ^2.9.0
  path: ^1.8.2
  intl: ^0.17.0
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
